# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UBports blog
email: blog@ubports.com
description: > # this means to ignore newlines until "baseurl:"
  UBports blog. Ubuntu touch porting to android devices
baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.ubports.com
twitter_username: ubports
github_username:  ubports

# Build settings
markdown: kramdown
destination: docs

exclude: [docs/CNAME]
keep_files: [docs/CNAME]
